workflows:
  android-workflow:
    name: Build Android APK
    environment:
      vars:
        JAVA_VERSION: 11
      android_signing:
        - keystore: my_keystore
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
