workflows:
  android-workflow:
    name: Build Debug APK
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
